/**
 * Tasks (Kensium "General Features" — Tasks/Messages/Notifications):
 * system-generated tasks routed by workflows plus manual tasks assigned
 * between employees, with escalation, confidentiality, reassignment and
 * reopen semantics. In-memory seed data; the store lives in hooks/use-tasks.ts.
 */

export type TaskStatus = 'Pending' | 'Completed' | 'Reassigned'
export type TaskSource = 'System' | 'Manual'
export type TaskType = 'Task' | 'Approval' | 'Review'

/** Module the Initiate action redirects to for system tasks. */
export type TaskModule = 'leave' | 'attendance' | 'recruitment' | 'other'

export interface TaskHistoryEntry {
  at: string
  event: string
}

export interface HrTask {
  id: string
  title: string
  comments: string
  taskType: TaskType
  source: TaskSource
  status: TaskStatus
  assignor: string
  assignee: string
  createdAt: string
  /** yyyy-mm-dd */
  dueDate: string
  /** Invoke-on date, when "Invoke task on" was checked. */
  invokeOn?: string
  remindDaysBefore?: number
  escalationRequired: boolean
  /** Escalation levels to walk up the hierarchy when overdue. */
  escalationLimit?: number
  /** Hidden from everyone except the assignor and the reporting manager. */
  confidential: boolean
  location?: string
  department?: string
  position?: string
  /** Transaction screen the Initiate action redirects to (system tasks). */
  linkedModule?: TaskModule
  linkedRecord?: string
  completedAt?: string
  completionComment?: string
  /** Populated on the frozen original record after a reassignment. */
  reassignedTo?: string
  /** Links a task created by a reassignment back to its original record. */
  reassignedFromId?: string
  history: TaskHistoryEntry[]
}

export const seedTasks: HrTask[] = [
  // ---- System tasks assigned to the signed-in persona (Dana Whitfield) ----
  {
    id: 'TSK-1001',
    title: 'Approve leave request — Priya Nair (LR-2214)',
    comments:
      'Workflow routed this approval to you as the reporting manager. Priya requested 3 days of casual leave (14–16 Jul).',
    taskType: 'Approval',
    source: 'System',
    status: 'Pending',
    assignor: 'System (Leave workflow)',
    assignee: 'Dana Whitfield',
    createdAt: '2026-07-02',
    dueDate: '2026-07-05',
    escalationRequired: true,
    escalationLimit: 2,
    confidential: false,
    linkedModule: 'leave',
    linkedRecord: 'Leave request LR-2214',
    history: [{ at: '2026-07-02', event: 'Task generated by the Leave approval workflow' }],
  },
  {
    id: 'TSK-1002',
    title: 'Approve attendance change request — Theo Brooks (CR-118)',
    comments:
      'Theo submitted a change request for a missed punch on 30 Jun. Approve or reject from the attendance screen.',
    taskType: 'Approval',
    source: 'System',
    status: 'Pending',
    assignor: 'System (Attendance workflow)',
    assignee: 'Dana Whitfield',
    createdAt: '2026-07-06',
    dueDate: '2026-07-10',
    escalationRequired: true,
    escalationLimit: 1,
    confidential: false,
    linkedModule: 'attendance',
    linkedRecord: 'Attendance CR-118',
    history: [{ at: '2026-07-06', event: 'Task generated by the Attendance CR workflow' }],
  },
  {
    id: 'TSK-1003',
    title: 'Review job vacancy — Frontend Engineer (JV-031)',
    comments:
      'The recruitment workflow needs your review of the Frontend Engineer vacancy before it is published.',
    taskType: 'Review',
    source: 'System',
    status: 'Pending',
    assignor: 'System (Recruitment workflow)',
    assignee: 'Dana Whitfield',
    createdAt: '2026-07-07',
    dueDate: '2026-07-12',
    escalationRequired: false,
    confidential: false,
    linkedModule: 'recruitment',
    linkedRecord: 'Job vacancy JV-031',
    history: [{ at: '2026-07-07', event: 'Task generated by the Recruitment workflow' }],
  },
  {
    id: 'TSK-1004',
    title: 'Approve expense claim — Marcus Lane (EXP-0981)',
    comments: 'Expense claim of $412.80 for the Austin client visit.',
    taskType: 'Approval',
    source: 'System',
    status: 'Completed',
    assignor: 'System (Expense workflow)',
    assignee: 'Dana Whitfield',
    createdAt: '2026-06-28',
    dueDate: '2026-07-01',
    escalationRequired: false,
    confidential: false,
    linkedModule: 'other',
    linkedRecord: 'Expense claim EXP-0981',
    completedAt: '2026-07-01',
    completionComment: 'Verified receipts and approved the claim.',
    history: [
      { at: '2026-06-28', event: 'Task generated by the Expense workflow' },
      { at: '2026-07-01', event: 'Marked complete by Dana Whitfield — stakeholders notified' },
    ],
  },
  // ---- Manual tasks assigned TO the signed-in persona ----
  {
    id: 'TSK-1005',
    title: 'Prepare Q3 headcount plan',
    comments:
      'Draft the Q3 headcount plan for Engineering (Hyderabad + London) and share before the leadership review.',
    taskType: 'Task',
    source: 'Manual',
    status: 'Pending',
    assignor: 'Rachel Kim',
    assignee: 'Dana Whitfield',
    createdAt: '2026-06-30',
    dueDate: '2026-07-08',
    remindDaysBefore: 2,
    escalationRequired: true,
    escalationLimit: 2,
    confidential: false,
    location: 'Hyderabad',
    department: 'Engineering',
    position: 'Engineering Manager',
    history: [{ at: '2026-06-30', event: 'Assigned by Rachel Kim' }],
  },
  {
    id: 'TSK-1006',
    title: 'Submit H1 self-appraisal',
    comments: 'Complete your H1 self-appraisal in the performance module.',
    taskType: 'Task',
    source: 'Manual',
    status: 'Completed',
    assignor: 'Rachel Kim',
    assignee: 'Dana Whitfield',
    createdAt: '2026-06-20',
    dueDate: '2026-06-30',
    escalationRequired: false,
    confidential: false,
    location: 'Hyderabad',
    department: 'Engineering',
    position: 'Engineering Manager',
    completedAt: '2026-06-29',
    completionComment: 'Self-appraisal submitted with supporting metrics.',
    history: [
      { at: '2026-06-20', event: 'Assigned by Rachel Kim' },
      { at: '2026-06-29', event: 'Marked complete by Dana Whitfield — stakeholders notified' },
    ],
  },
  {
    id: 'TSK-1007',
    title: 'Coordinate London office all-hands logistics',
    comments:
      'Originally assigned to you; reassigned to Amara Okafor who is on-site in London.',
    taskType: 'Task',
    source: 'Manual',
    status: 'Reassigned',
    assignor: 'Rachel Kim',
    assignee: 'Dana Whitfield',
    createdAt: '2026-06-25',
    dueDate: '2026-07-14',
    escalationRequired: false,
    confidential: false,
    location: 'London',
    department: 'Engineering',
    position: 'Software Engineer',
    reassignedTo: 'Amara Okafor',
    history: [
      { at: '2026-06-25', event: 'Assigned by Rachel Kim' },
      { at: '2026-07-03', event: 'Reassigned to Amara Okafor by Rachel Kim' },
    ],
  },
  // ---- Manual tasks assigned BY the signed-in persona ----
  {
    id: 'TSK-2001',
    title: 'Update onboarding checklist for Sofia Reyes',
    comments:
      'Refresh the pre-joining checklist (laptop, access badges, mailbox) before Sofia joins on 07 Jul.',
    taskType: 'Task',
    source: 'Manual',
    status: 'Pending',
    assignor: 'Dana Whitfield',
    assignee: 'Liam Patel',
    createdAt: '2026-07-01',
    dueDate: '2026-07-06',
    remindDaysBefore: 1,
    escalationRequired: false,
    confidential: false,
    location: 'Hyderabad',
    department: 'Human Resources',
    position: 'HR Executive',
    history: [{ at: '2026-07-01', event: 'Assigned by Dana Whitfield' }],
  },
  {
    id: 'TSK-2002',
    title: 'Compile monthly attrition report',
    comments:
      'Pull June attrition numbers by department and add commentary for outliers.',
    taskType: 'Task',
    source: 'Manual',
    status: 'Pending',
    assignor: 'Dana Whitfield',
    assignee: 'Priya Nair',
    createdAt: '2026-07-05',
    dueDate: '2026-07-15',
    invokeOn: '2026-07-10',
    remindDaysBefore: 3,
    escalationRequired: true,
    escalationLimit: 1,
    confidential: false,
    location: 'Hyderabad',
    department: 'Engineering',
    position: 'Software Engineer',
    history: [{ at: '2026-07-05', event: 'Assigned by Dana Whitfield (invokes on 10 Jul)' }],
  },
  {
    id: 'TSK-2003',
    title: 'Draft PIP documentation for a Support hire',
    comments:
      'Confidential: prepare the draft performance-improvement documentation for HR review.',
    taskType: 'Task',
    source: 'Manual',
    status: 'Pending',
    assignor: 'Dana Whitfield',
    assignee: 'Liam Patel',
    createdAt: '2026-07-04',
    dueDate: '2026-07-20',
    escalationRequired: false,
    confidential: true,
    location: 'Hyderabad',
    department: 'Human Resources',
    position: 'HR Executive',
    history: [{ at: '2026-07-04', event: 'Assigned confidentially by Dana Whitfield' }],
  },
  {
    id: 'TSK-2004',
    title: 'Run QA regression suite for release 4.2',
    comments: 'Full regression on staging; log defects against the 4.2 board.',
    taskType: 'Task',
    source: 'Manual',
    status: 'Completed',
    assignor: 'Dana Whitfield',
    assignee: 'Theo Brooks',
    createdAt: '2026-06-27',
    dueDate: '2026-07-03',
    escalationRequired: false,
    confidential: false,
    location: 'Hyderabad',
    department: 'Engineering',
    position: 'QA Analyst',
    completedAt: '2026-07-03',
    completionComment: 'Regression complete — 2 minor defects logged (BUG-771, BUG-772).',
    history: [
      { at: '2026-06-27', event: 'Assigned by Dana Whitfield' },
      { at: '2026-07-03', event: 'Marked complete by Theo Brooks — stakeholders notified' },
    ],
  },
  {
    id: 'TSK-2005',
    title: 'Prepare Q3 partner sales deck',
    comments: 'Original assignment; reassigned after territory changes.',
    taskType: 'Task',
    source: 'Manual',
    status: 'Reassigned',
    assignor: 'Dana Whitfield',
    assignee: 'Marcus Lane',
    createdAt: '2026-06-29',
    dueDate: '2026-07-11',
    escalationRequired: false,
    confidential: false,
    location: 'Austin',
    department: 'Sales',
    position: 'Account Executive',
    reassignedTo: 'Elena Petrova',
    history: [
      { at: '2026-06-29', event: 'Assigned by Dana Whitfield' },
      { at: '2026-07-02', event: 'Reassigned to Elena Petrova by Dana Whitfield' },
    ],
  },
  {
    id: 'TSK-2006',
    title: 'Prepare Q3 partner sales deck',
    comments:
      'Reassigned from Marcus Lane after territory changes. Build the Q3 partner deck with updated pricing tiers.',
    taskType: 'Task',
    source: 'Manual',
    status: 'Pending',
    assignor: 'Dana Whitfield',
    assignee: 'Elena Petrova',
    createdAt: '2026-07-02',
    dueDate: '2026-07-11',
    remindDaysBefore: 2,
    escalationRequired: false,
    confidential: false,
    location: 'Austin',
    department: 'Sales',
    position: 'Sales Manager',
    reassignedFromId: 'TSK-2005',
    history: [{ at: '2026-07-02', event: 'Created by reassignment from Marcus Lane' }],
  },
]
