import { useEffect, useMemo } from 'react'
import { z } from 'zod'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Button } from '@/components/ui/button'
import { FloatingSheetContent } from '@/components/ui/floating-sheet-content'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Sheet, SheetHeader, SheetTitle } from '@/components/ui/sheet'
import { type ReportDef } from '../data/report-catalog'
import {
  SCHEDULE_FORMATS,
  SCHEDULE_FREQUENCIES,
  type ReportSchedule,
} from '../data/schedules'
import { type ScheduleDraft } from '../hooks/use-schedules'

const emailList = z
  .string()
  .min(3, 'Add at least one recipient')
  .refine(
    (v) =>
      v
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean)
        .every((s) => z.email().safeParse(s).success),
    'Enter valid email addresses separated by commas'
  )

const scheduleSchema = z.object({
  reportName: z.string().min(1, 'Choose a report'),
  frequency: z.enum(SCHEDULE_FREQUENCIES),
  time: z
    .string()
    .regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'Use 24h time, e.g. 07:30'),
  recipients: emailList,
  format: z.enum(SCHEDULE_FORMATS),
})

type ScheduleFormValues = z.infer<typeof scheduleSchema>

const emptyValues: ScheduleFormValues = {
  reportName: '',
  frequency: 'Weekly',
  time: '08:00',
  recipients: '',
  format: 'XLSX',
}

interface ScheduleOverlayProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  /** Existing schedule to edit; otherwise creates a new one (RPT-09). */
  schedule?: ReportSchedule | null
  /** Preselects the report when scheduling from the catalog run sheet. */
  presetReport?: string | null
  reports: ReportDef[]
  createdBy: string
  scope: string
  onSubmit: (draft: ScheduleDraft) => void
}

/** Configure email delivery: frequency, time, recipients, format (RPT-09). */
export function ScheduleOverlay({
  open,
  onOpenChange,
  schedule,
  presetReport,
  reports,
  createdBy,
  scope,
  onSubmit,
}: ScheduleOverlayProps) {
  const isEdit = Boolean(schedule)

  const form = useForm<ScheduleFormValues>({
    resolver: zodResolver(scheduleSchema),
    defaultValues: emptyValues,
  })

  useEffect(() => {
    if (!open) return
    form.reset(
      schedule
        ? {
            reportName: schedule.reportName,
            frequency: schedule.frequency,
            time: schedule.time,
            recipients: schedule.recipients.join(', '),
            format: schedule.format,
          }
        : { ...emptyValues, reportName: presetReport ?? '' }
    )
  }, [open, schedule, presetReport, form])

  const enabledReports = useMemo(
    () => reports.filter((r) => r.enabled),
    [reports]
  )

  const handleSubmit = (values: ScheduleFormValues) => {
    onSubmit({
      reportName: values.reportName,
      frequency: values.frequency,
      time: values.time,
      recipients: values.recipients
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean),
      format: values.format,
      createdBy,
      scope,
    })
    onOpenChange(false)
  }

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <FloatingSheetContent className='flex w-full flex-col gap-0 p-0 sm:max-w-[460px]'>
        <SheetHeader className='border-gray-200 border-b px-5 py-4'>
          <SheetTitle className='text-neutral-1600 text-paragraph-md font-semibold'>
            {isEdit ? 'Edit schedule' : 'New scheduled delivery'}
          </SheetTitle>
          <p className='text-paragraph-sm text-neutral-1000'>
            Deliveries are generated by the Notification/Template engine and
            respect your company access scope ({scope}).
          </p>
        </SheetHeader>

        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(handleSubmit)}
            className='flex min-h-0 flex-1 flex-col'
          >
            <div className='flex-1 space-y-4 overflow-y-auto px-5 py-5'>
              <FormField
                control={form.control}
                name='reportName'
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Report</FormLabel>
                    <Select value={field.value} onValueChange={field.onChange}>
                      <FormControl>
                        <SelectTrigger variant='secondary' className='w-full'>
                          <SelectValue placeholder='Choose a report' />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {enabledReports.map((r) => (
                          <SelectItem key={r.id} value={r.name}>
                            {r.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name='frequency'
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Frequency</FormLabel>
                    <Select value={field.value} onValueChange={field.onChange}>
                      <FormControl>
                        <SelectTrigger variant='secondary' className='w-full'>
                          <SelectValue />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {SCHEDULE_FREQUENCIES.map((f) => (
                          <SelectItem key={f} value={f}>
                            {f}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name='time'
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Delivery time (24h)</FormLabel>
                    <FormControl>
                      <Input placeholder='07:30' {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name='recipients'
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Recipients (comma separated)</FormLabel>
                    <FormControl>
                      <Input
                        placeholder='hr-ops@aurora.example, cfo@aurora.example'
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name='format'
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Attachment format</FormLabel>
                    <Select value={field.value} onValueChange={field.onChange}>
                      <FormControl>
                        <SelectTrigger variant='secondary' className='w-full'>
                          <SelectValue />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {SCHEDULE_FORMATS.map((f) => (
                          <SelectItem key={f} value={f}>
                            {f}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className='border-gray-200 flex items-center justify-end gap-3 border-t px-5 py-4'>
              <Button
                type='button'
                variant='outline'
                onClick={() => onOpenChange(false)}
              >
                Cancel
              </Button>
              <Button type='submit'>
                {isEdit ? 'Save changes' : 'Create schedule'}
              </Button>
            </div>
          </form>
        </Form>
      </FloatingSheetContent>
    </Sheet>
  )
}
