/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSelfServiceIndexRouteImport } from './routes/_authenticated/self-service/index'
import { Route as AuthenticatedRolesSecurityIndexRouteImport } from './routes/_authenticated/roles-security/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedRecruitmentIndexRouteImport } from './routes/_authenticated/recruitment/index'
import { Route as AuthenticatedPositionsIndexRouteImport } from './routes/_authenticated/positions/index'
import { Route as AuthenticatedPortfoliosIndexRouteImport } from './routes/_authenticated/portfolios/index'
import { Route as AuthenticatedPolicyDistributionIndexRouteImport } from './routes/_authenticated/policy-distribution/index'
import { Route as AuthenticatedPoliciesIndexRouteImport } from './routes/_authenticated/policies/index'
import { Route as AuthenticatedPlatformAdminIndexRouteImport } from './routes/_authenticated/platform-admin/index'
import { Route as AuthenticatedOrgGroupsIndexRouteImport } from './routes/_authenticated/org-groups/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations/index'
import { Route as AuthenticatedLifecycleIndexRouteImport } from './routes/_authenticated/lifecycle/index'
import { Route as AuthenticatedLeaveIndexRouteImport } from './routes/_authenticated/leave/index'
import { Route as AuthenticatedJurisdictionsIndexRouteImport } from './routes/_authenticated/jurisdictions/index'
import { Route as AuthenticatedHrLettersIndexRouteImport } from './routes/_authenticated/hr-letters/index'
import { Route as AuthenticatedGroupCompaniesIndexRouteImport } from './routes/_authenticated/group-companies/index'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback/index'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedDirectoryIndexRouteImport } from './routes/_authenticated/directory/index'
import { Route as AuthenticatedDepartmentsIndexRouteImport } from './routes/_authenticated/departments/index'
import { Route as AuthenticatedDataManagementIndexRouteImport } from './routes/_authenticated/data-management/index'
import { Route as AuthenticatedCustomFieldsIndexRouteImport } from './routes/_authenticated/custom-fields/index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies/index'
import { Route as AuthenticatedAuthenticationIndexRouteImport } from './routes/_authenticated/authentication/index'
import { Route as AuthenticatedAuditLogsIndexRouteImport } from './routes/_authenticated/audit-logs/index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets/index'
import { Route as AuthenticatedAnnouncementsIndexRouteImport } from './routes/_authenticated/announcements/index'
import { Route as AuthenticatedPlatformAdminWorkspaceRouteImport } from './routes/_authenticated/platform-admin/workspace'
import { Route as AuthenticatedPlatformAdminOrgModelRouteImport } from './routes/_authenticated/platform-admin/org-model'
import { Route as AuthenticatedEmployeesPerformanceRouteImport } from './routes/_authenticated/employees/performance'
import { Route as AuthenticatedEmployeesLifecycleRouteImport } from './routes/_authenticated/employees/lifecycle'
import { Route as AuthenticatedEmployeesConfigurationRouteImport } from './routes/_authenticated/employees/configuration'
import { Route as AuthenticatedReportsCurrentStatusIndexRouteImport } from './routes/_authenticated/reports/current-status/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelfServiceIndexRoute =
  AuthenticatedSelfServiceIndexRouteImport.update({
    id: '/self-service/',
    path: '/self-service/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesSecurityIndexRoute =
  AuthenticatedRolesSecurityIndexRouteImport.update({
    id: '/roles-security/',
    path: '/roles-security/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruitmentIndexRoute =
  AuthenticatedRecruitmentIndexRouteImport.update({
    id: '/recruitment/',
    path: '/recruitment/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPositionsIndexRoute =
  AuthenticatedPositionsIndexRouteImport.update({
    id: '/positions/',
    path: '/positions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortfoliosIndexRoute =
  AuthenticatedPortfoliosIndexRouteImport.update({
    id: '/portfolios/',
    path: '/portfolios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPolicyDistributionIndexRoute =
  AuthenticatedPolicyDistributionIndexRouteImport.update({
    id: '/policy-distribution/',
    path: '/policy-distribution/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoliciesIndexRoute =
  AuthenticatedPoliciesIndexRouteImport.update({
    id: '/policies/',
    path: '/policies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformAdminIndexRoute =
  AuthenticatedPlatformAdminIndexRouteImport.update({
    id: '/platform-admin/',
    path: '/platform-admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgGroupsIndexRoute =
  AuthenticatedOrgGroupsIndexRouteImport.update({
    id: '/org-groups/',
    path: '/org-groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLifecycleIndexRoute =
  AuthenticatedLifecycleIndexRouteImport.update({
    id: '/lifecycle/',
    path: '/lifecycle/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveIndexRoute = AuthenticatedLeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJurisdictionsIndexRoute =
  AuthenticatedJurisdictionsIndexRouteImport.update({
    id: '/jurisdictions/',
    path: '/jurisdictions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrLettersIndexRoute =
  AuthenticatedHrLettersIndexRouteImport.update({
    id: '/hr-letters/',
    path: '/hr-letters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupCompaniesIndexRoute =
  AuthenticatedGroupCompaniesIndexRouteImport.update({
    id: '/group-companies/',
    path: '/group-companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDirectoryIndexRoute =
  AuthenticatedDirectoryIndexRouteImport.update({
    id: '/directory/',
    path: '/directory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsIndexRoute =
  AuthenticatedDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataManagementIndexRoute =
  AuthenticatedDataManagementIndexRouteImport.update({
    id: '/data-management/',
    path: '/data-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomFieldsIndexRoute =
  AuthenticatedCustomFieldsIndexRouteImport.update({
    id: '/custom-fields/',
    path: '/custom-fields/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuthenticationIndexRoute =
  AuthenticatedAuthenticationIndexRouteImport.update({
    id: '/authentication/',
    path: '/authentication/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogsIndexRoute =
  AuthenticatedAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnnouncementsIndexRoute =
  AuthenticatedAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformAdminWorkspaceRoute =
  AuthenticatedPlatformAdminWorkspaceRouteImport.update({
    id: '/platform-admin/workspace',
    path: '/platform-admin/workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformAdminOrgModelRoute =
  AuthenticatedPlatformAdminOrgModelRouteImport.update({
    id: '/platform-admin/org-model',
    path: '/platform-admin/org-model',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesPerformanceRoute =
  AuthenticatedEmployeesPerformanceRouteImport.update({
    id: '/employees/performance',
    path: '/employees/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesLifecycleRoute =
  AuthenticatedEmployeesLifecycleRouteImport.update({
    id: '/employees/lifecycle',
    path: '/employees/lifecycle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesConfigurationRoute =
  AuthenticatedEmployeesConfigurationRouteImport.update({
    id: '/employees/configuration',
    path: '/employees/configuration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsCurrentStatusIndexRoute =
  AuthenticatedReportsCurrentStatusIndexRouteImport.update({
    id: '/reports/current-status/',
    path: '/reports/current-status/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/employees/configuration': typeof AuthenticatedEmployeesConfigurationRoute
  '/employees/lifecycle': typeof AuthenticatedEmployeesLifecycleRoute
  '/employees/performance': typeof AuthenticatedEmployeesPerformanceRoute
  '/platform-admin/org-model': typeof AuthenticatedPlatformAdminOrgModelRoute
  '/platform-admin/workspace': typeof AuthenticatedPlatformAdminWorkspaceRoute
  '/announcements': typeof AuthenticatedAnnouncementsIndexRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/authentication': typeof AuthenticatedAuthenticationIndexRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/custom-fields': typeof AuthenticatedCustomFieldsIndexRoute
  '/data-management': typeof AuthenticatedDataManagementIndexRoute
  '/departments': typeof AuthenticatedDepartmentsIndexRoute
  '/directory': typeof AuthenticatedDirectoryIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/group-companies': typeof AuthenticatedGroupCompaniesIndexRoute
  '/hr-letters': typeof AuthenticatedHrLettersIndexRoute
  '/jurisdictions': typeof AuthenticatedJurisdictionsIndexRoute
  '/leave': typeof AuthenticatedLeaveIndexRoute
  '/lifecycle': typeof AuthenticatedLifecycleIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/org-groups': typeof AuthenticatedOrgGroupsIndexRoute
  '/platform-admin': typeof AuthenticatedPlatformAdminIndexRoute
  '/policies': typeof AuthenticatedPoliciesIndexRoute
  '/policy-distribution': typeof AuthenticatedPolicyDistributionIndexRoute
  '/portfolios': typeof AuthenticatedPortfoliosIndexRoute
  '/positions': typeof AuthenticatedPositionsIndexRoute
  '/recruitment': typeof AuthenticatedRecruitmentIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/roles-security': typeof AuthenticatedRolesSecurityIndexRoute
  '/self-service': typeof AuthenticatedSelfServiceIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/reports/current-status': typeof AuthenticatedReportsCurrentStatusIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/employees/configuration': typeof AuthenticatedEmployeesConfigurationRoute
  '/employees/lifecycle': typeof AuthenticatedEmployeesLifecycleRoute
  '/employees/performance': typeof AuthenticatedEmployeesPerformanceRoute
  '/platform-admin/org-model': typeof AuthenticatedPlatformAdminOrgModelRoute
  '/platform-admin/workspace': typeof AuthenticatedPlatformAdminWorkspaceRoute
  '/announcements': typeof AuthenticatedAnnouncementsIndexRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/authentication': typeof AuthenticatedAuthenticationIndexRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/custom-fields': typeof AuthenticatedCustomFieldsIndexRoute
  '/data-management': typeof AuthenticatedDataManagementIndexRoute
  '/departments': typeof AuthenticatedDepartmentsIndexRoute
  '/directory': typeof AuthenticatedDirectoryIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/group-companies': typeof AuthenticatedGroupCompaniesIndexRoute
  '/hr-letters': typeof AuthenticatedHrLettersIndexRoute
  '/jurisdictions': typeof AuthenticatedJurisdictionsIndexRoute
  '/leave': typeof AuthenticatedLeaveIndexRoute
  '/lifecycle': typeof AuthenticatedLifecycleIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/org-groups': typeof AuthenticatedOrgGroupsIndexRoute
  '/platform-admin': typeof AuthenticatedPlatformAdminIndexRoute
  '/policies': typeof AuthenticatedPoliciesIndexRoute
  '/policy-distribution': typeof AuthenticatedPolicyDistributionIndexRoute
  '/portfolios': typeof AuthenticatedPortfoliosIndexRoute
  '/positions': typeof AuthenticatedPositionsIndexRoute
  '/recruitment': typeof AuthenticatedRecruitmentIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/roles-security': typeof AuthenticatedRolesSecurityIndexRoute
  '/self-service': typeof AuthenticatedSelfServiceIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/reports/current-status': typeof AuthenticatedReportsCurrentStatusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/employees/configuration': typeof AuthenticatedEmployeesConfigurationRoute
  '/_authenticated/employees/lifecycle': typeof AuthenticatedEmployeesLifecycleRoute
  '/_authenticated/employees/performance': typeof AuthenticatedEmployeesPerformanceRoute
  '/_authenticated/platform-admin/org-model': typeof AuthenticatedPlatformAdminOrgModelRoute
  '/_authenticated/platform-admin/workspace': typeof AuthenticatedPlatformAdminWorkspaceRoute
  '/_authenticated/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/_authenticated/authentication/': typeof AuthenticatedAuthenticationIndexRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/custom-fields/': typeof AuthenticatedCustomFieldsIndexRoute
  '/_authenticated/data-management/': typeof AuthenticatedDataManagementIndexRoute
  '/_authenticated/departments/': typeof AuthenticatedDepartmentsIndexRoute
  '/_authenticated/directory/': typeof AuthenticatedDirectoryIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/_authenticated/group-companies/': typeof AuthenticatedGroupCompaniesIndexRoute
  '/_authenticated/hr-letters/': typeof AuthenticatedHrLettersIndexRoute
  '/_authenticated/jurisdictions/': typeof AuthenticatedJurisdictionsIndexRoute
  '/_authenticated/leave/': typeof AuthenticatedLeaveIndexRoute
  '/_authenticated/lifecycle/': typeof AuthenticatedLifecycleIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/org-groups/': typeof AuthenticatedOrgGroupsIndexRoute
  '/_authenticated/platform-admin/': typeof AuthenticatedPlatformAdminIndexRoute
  '/_authenticated/policies/': typeof AuthenticatedPoliciesIndexRoute
  '/_authenticated/policy-distribution/': typeof AuthenticatedPolicyDistributionIndexRoute
  '/_authenticated/portfolios/': typeof AuthenticatedPortfoliosIndexRoute
  '/_authenticated/positions/': typeof AuthenticatedPositionsIndexRoute
  '/_authenticated/recruitment/': typeof AuthenticatedRecruitmentIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/roles-security/': typeof AuthenticatedRolesSecurityIndexRoute
  '/_authenticated/self-service/': typeof AuthenticatedSelfServiceIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/_authenticated/reports/current-status/': typeof AuthenticatedReportsCurrentStatusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/employees/configuration'
    | '/employees/lifecycle'
    | '/employees/performance'
    | '/platform-admin/org-model'
    | '/platform-admin/workspace'
    | '/announcements'
    | '/assets'
    | '/attendance'
    | '/audit-logs'
    | '/authentication'
    | '/companies'
    | '/custom-fields'
    | '/data-management'
    | '/departments'
    | '/directory'
    | '/documents'
    | '/employees'
    | '/feedback'
    | '/group-companies'
    | '/hr-letters'
    | '/jurisdictions'
    | '/leave'
    | '/lifecycle'
    | '/locations'
    | '/notifications'
    | '/org-groups'
    | '/platform-admin'
    | '/policies'
    | '/policy-distribution'
    | '/portfolios'
    | '/positions'
    | '/recruitment'
    | '/reports'
    | '/roles-security'
    | '/self-service'
    | '/users'
    | '/workflows'
    | '/reports/current-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/employees/configuration'
    | '/employees/lifecycle'
    | '/employees/performance'
    | '/platform-admin/org-model'
    | '/platform-admin/workspace'
    | '/announcements'
    | '/assets'
    | '/attendance'
    | '/audit-logs'
    | '/authentication'
    | '/companies'
    | '/custom-fields'
    | '/data-management'
    | '/departments'
    | '/directory'
    | '/documents'
    | '/employees'
    | '/feedback'
    | '/group-companies'
    | '/hr-letters'
    | '/jurisdictions'
    | '/leave'
    | '/lifecycle'
    | '/locations'
    | '/notifications'
    | '/org-groups'
    | '/platform-admin'
    | '/policies'
    | '/policy-distribution'
    | '/portfolios'
    | '/positions'
    | '/recruitment'
    | '/reports'
    | '/roles-security'
    | '/self-service'
    | '/users'
    | '/workflows'
    | '/reports/current-status'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/employees/configuration'
    | '/_authenticated/employees/lifecycle'
    | '/_authenticated/employees/performance'
    | '/_authenticated/platform-admin/org-model'
    | '/_authenticated/platform-admin/workspace'
    | '/_authenticated/announcements/'
    | '/_authenticated/assets/'
    | '/_authenticated/attendance/'
    | '/_authenticated/audit-logs/'
    | '/_authenticated/authentication/'
    | '/_authenticated/companies/'
    | '/_authenticated/custom-fields/'
    | '/_authenticated/data-management/'
    | '/_authenticated/departments/'
    | '/_authenticated/directory/'
    | '/_authenticated/documents/'
    | '/_authenticated/employees/'
    | '/_authenticated/feedback/'
    | '/_authenticated/group-companies/'
    | '/_authenticated/hr-letters/'
    | '/_authenticated/jurisdictions/'
    | '/_authenticated/leave/'
    | '/_authenticated/lifecycle/'
    | '/_authenticated/locations/'
    | '/_authenticated/notifications/'
    | '/_authenticated/org-groups/'
    | '/_authenticated/platform-admin/'
    | '/_authenticated/policies/'
    | '/_authenticated/policy-distribution/'
    | '/_authenticated/portfolios/'
    | '/_authenticated/positions/'
    | '/_authenticated/recruitment/'
    | '/_authenticated/reports/'
    | '/_authenticated/roles-security/'
    | '/_authenticated/self-service/'
    | '/_authenticated/users/'
    | '/_authenticated/workflows/'
    | '/_authenticated/reports/current-status/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/self-service/': {
      id: '/_authenticated/self-service/'
      path: '/self-service'
      fullPath: '/self-service'
      preLoaderRoute: typeof AuthenticatedSelfServiceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles-security/': {
      id: '/_authenticated/roles-security/'
      path: '/roles-security'
      fullPath: '/roles-security'
      preLoaderRoute: typeof AuthenticatedRolesSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruitment/': {
      id: '/_authenticated/recruitment/'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AuthenticatedRecruitmentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions/': {
      id: '/_authenticated/positions/'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolios/': {
      id: '/_authenticated/portfolios/'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof AuthenticatedPortfoliosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policy-distribution/': {
      id: '/_authenticated/policy-distribution/'
      path: '/policy-distribution'
      fullPath: '/policy-distribution'
      preLoaderRoute: typeof AuthenticatedPolicyDistributionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies/': {
      id: '/_authenticated/policies/'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-admin/': {
      id: '/_authenticated/platform-admin/'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof AuthenticatedPlatformAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org-groups/': {
      id: '/_authenticated/org-groups/'
      path: '/org-groups'
      fullPath: '/org-groups'
      preLoaderRoute: typeof AuthenticatedOrgGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lifecycle/': {
      id: '/_authenticated/lifecycle/'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof AuthenticatedLifecycleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave/': {
      id: '/_authenticated/leave/'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jurisdictions/': {
      id: '/_authenticated/jurisdictions/'
      path: '/jurisdictions'
      fullPath: '/jurisdictions'
      preLoaderRoute: typeof AuthenticatedJurisdictionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr-letters/': {
      id: '/_authenticated/hr-letters/'
      path: '/hr-letters'
      fullPath: '/hr-letters'
      preLoaderRoute: typeof AuthenticatedHrLettersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/group-companies/': {
      id: '/_authenticated/group-companies/'
      path: '/group-companies'
      fullPath: '/group-companies'
      preLoaderRoute: typeof AuthenticatedGroupCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directory/': {
      id: '/_authenticated/directory/'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments/': {
      id: '/_authenticated/departments/'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-management/': {
      id: '/_authenticated/data-management/'
      path: '/data-management'
      fullPath: '/data-management'
      preLoaderRoute: typeof AuthenticatedDataManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custom-fields/': {
      id: '/_authenticated/custom-fields/'
      path: '/custom-fields'
      fullPath: '/custom-fields'
      preLoaderRoute: typeof AuthenticatedCustomFieldsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/authentication/': {
      id: '/_authenticated/authentication/'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticatedAuthenticationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs/': {
      id: '/_authenticated/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements/': {
      id: '/_authenticated/announcements/'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-admin/workspace': {
      id: '/_authenticated/platform-admin/workspace'
      path: '/platform-admin/workspace'
      fullPath: '/platform-admin/workspace'
      preLoaderRoute: typeof AuthenticatedPlatformAdminWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-admin/org-model': {
      id: '/_authenticated/platform-admin/org-model'
      path: '/platform-admin/org-model'
      fullPath: '/platform-admin/org-model'
      preLoaderRoute: typeof AuthenticatedPlatformAdminOrgModelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/performance': {
      id: '/_authenticated/employees/performance'
      path: '/employees/performance'
      fullPath: '/employees/performance'
      preLoaderRoute: typeof AuthenticatedEmployeesPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/lifecycle': {
      id: '/_authenticated/employees/lifecycle'
      path: '/employees/lifecycle'
      fullPath: '/employees/lifecycle'
      preLoaderRoute: typeof AuthenticatedEmployeesLifecycleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/configuration': {
      id: '/_authenticated/employees/configuration'
      path: '/employees/configuration'
      fullPath: '/employees/configuration'
      preLoaderRoute: typeof AuthenticatedEmployeesConfigurationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/current-status/': {
      id: '/_authenticated/reports/current-status/'
      path: '/reports/current-status'
      fullPath: '/reports/current-status'
      preLoaderRoute: typeof AuthenticatedReportsCurrentStatusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEmployeesConfigurationRoute: typeof AuthenticatedEmployeesConfigurationRoute
  AuthenticatedEmployeesLifecycleRoute: typeof AuthenticatedEmployeesLifecycleRoute
  AuthenticatedEmployeesPerformanceRoute: typeof AuthenticatedEmployeesPerformanceRoute
  AuthenticatedPlatformAdminOrgModelRoute: typeof AuthenticatedPlatformAdminOrgModelRoute
  AuthenticatedPlatformAdminWorkspaceRoute: typeof AuthenticatedPlatformAdminWorkspaceRoute
  AuthenticatedAnnouncementsIndexRoute: typeof AuthenticatedAnnouncementsIndexRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedAuditLogsIndexRoute: typeof AuthenticatedAuditLogsIndexRoute
  AuthenticatedAuthenticationIndexRoute: typeof AuthenticatedAuthenticationIndexRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedCustomFieldsIndexRoute: typeof AuthenticatedCustomFieldsIndexRoute
  AuthenticatedDataManagementIndexRoute: typeof AuthenticatedDataManagementIndexRoute
  AuthenticatedDepartmentsIndexRoute: typeof AuthenticatedDepartmentsIndexRoute
  AuthenticatedDirectoryIndexRoute: typeof AuthenticatedDirectoryIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
  AuthenticatedGroupCompaniesIndexRoute: typeof AuthenticatedGroupCompaniesIndexRoute
  AuthenticatedHrLettersIndexRoute: typeof AuthenticatedHrLettersIndexRoute
  AuthenticatedJurisdictionsIndexRoute: typeof AuthenticatedJurisdictionsIndexRoute
  AuthenticatedLeaveIndexRoute: typeof AuthenticatedLeaveIndexRoute
  AuthenticatedLifecycleIndexRoute: typeof AuthenticatedLifecycleIndexRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedOrgGroupsIndexRoute: typeof AuthenticatedOrgGroupsIndexRoute
  AuthenticatedPlatformAdminIndexRoute: typeof AuthenticatedPlatformAdminIndexRoute
  AuthenticatedPoliciesIndexRoute: typeof AuthenticatedPoliciesIndexRoute
  AuthenticatedPolicyDistributionIndexRoute: typeof AuthenticatedPolicyDistributionIndexRoute
  AuthenticatedPortfoliosIndexRoute: typeof AuthenticatedPortfoliosIndexRoute
  AuthenticatedPositionsIndexRoute: typeof AuthenticatedPositionsIndexRoute
  AuthenticatedRecruitmentIndexRoute: typeof AuthenticatedRecruitmentIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedRolesSecurityIndexRoute: typeof AuthenticatedRolesSecurityIndexRoute
  AuthenticatedSelfServiceIndexRoute: typeof AuthenticatedSelfServiceIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
  AuthenticatedReportsCurrentStatusIndexRoute: typeof AuthenticatedReportsCurrentStatusIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEmployeesConfigurationRoute:
    AuthenticatedEmployeesConfigurationRoute,
  AuthenticatedEmployeesLifecycleRoute: AuthenticatedEmployeesLifecycleRoute,
  AuthenticatedEmployeesPerformanceRoute:
    AuthenticatedEmployeesPerformanceRoute,
  AuthenticatedPlatformAdminOrgModelRoute:
    AuthenticatedPlatformAdminOrgModelRoute,
  AuthenticatedPlatformAdminWorkspaceRoute:
    AuthenticatedPlatformAdminWorkspaceRoute,
  AuthenticatedAnnouncementsIndexRoute: AuthenticatedAnnouncementsIndexRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedAuditLogsIndexRoute: AuthenticatedAuditLogsIndexRoute,
  AuthenticatedAuthenticationIndexRoute: AuthenticatedAuthenticationIndexRoute,
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedCustomFieldsIndexRoute: AuthenticatedCustomFieldsIndexRoute,
  AuthenticatedDataManagementIndexRoute: AuthenticatedDataManagementIndexRoute,
  AuthenticatedDepartmentsIndexRoute: AuthenticatedDepartmentsIndexRoute,
  AuthenticatedDirectoryIndexRoute: AuthenticatedDirectoryIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
  AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
  AuthenticatedGroupCompaniesIndexRoute: AuthenticatedGroupCompaniesIndexRoute,
  AuthenticatedHrLettersIndexRoute: AuthenticatedHrLettersIndexRoute,
  AuthenticatedJurisdictionsIndexRoute: AuthenticatedJurisdictionsIndexRoute,
  AuthenticatedLeaveIndexRoute: AuthenticatedLeaveIndexRoute,
  AuthenticatedLifecycleIndexRoute: AuthenticatedLifecycleIndexRoute,
  AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedOrgGroupsIndexRoute: AuthenticatedOrgGroupsIndexRoute,
  AuthenticatedPlatformAdminIndexRoute: AuthenticatedPlatformAdminIndexRoute,
  AuthenticatedPoliciesIndexRoute: AuthenticatedPoliciesIndexRoute,
  AuthenticatedPolicyDistributionIndexRoute:
    AuthenticatedPolicyDistributionIndexRoute,
  AuthenticatedPortfoliosIndexRoute: AuthenticatedPortfoliosIndexRoute,
  AuthenticatedPositionsIndexRoute: AuthenticatedPositionsIndexRoute,
  AuthenticatedRecruitmentIndexRoute: AuthenticatedRecruitmentIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedRolesSecurityIndexRoute: AuthenticatedRolesSecurityIndexRoute,
  AuthenticatedSelfServiceIndexRoute: AuthenticatedSelfServiceIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
  AuthenticatedReportsCurrentStatusIndexRoute:
    AuthenticatedReportsCurrentStatusIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
