import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await (await browser.newContext({ viewport: { width: 1500, height: 950 } })).newPage()
await page.goto('http://localhost:5174'); await page.waitForTimeout(900)
await page.locator('aside button').last().click(); await page.waitForTimeout(250)
await page.getByRole('button', { name: /David Chen/ }).first().click(); await page.waitForTimeout(600)
await page.goto('http://localhost:5174/#/rules'); await page.waitForTimeout(600)
await page.getByRole('button', { name: /New policy/ }).click(); await page.waitForTimeout(500)
await page.locator('.animate-slide-in').getByText('Hiring Service Levels', { exact: true }).first().click()
await page.waitForTimeout(450)
const t = await page.locator('.animate-slide-in').last().innerText()
console.log('AFTER TEMPLATE CLICK, drawer contains:')
console.log(t.slice(0, 600).replace(/\n+/g, ' | '))
const btns = await page.locator('.animate-slide-in button').allInnerTexts()
console.log('BUTTONS:', btns.filter(b => b.trim()).slice(0, 20).join(' / '))
await browser.close()
