// ---------------------------------------------------------------------------
// Recruitment configuration metadata (TA-15/16/25/26/35/37/38/40/41/43/46/48/
// 51/52/53/54/55/56) — versioned, effective-dated config the engines read.
// ---------------------------------------------------------------------------

export const LETTER_TYPES = [
  'Offer',
  'Appointment',
  'Joining',
  'Cancel Offer',
  'Confirmation',
  'Probation Extension',
] as const
export type LetterType = (typeof LETTER_TYPES)[number]

/** Offer/appointment/joining/cancel-offer letter template (TA-15, TA-48). */
export interface LetterTemplate {
  id: string
  letterType: LetterType
  name: string
  description: string
  /** Letter header — the company logo renders inside the header block. */
  header?: string
  content: string
  footer?: string
  mergeFields: string[]
  active: boolean
  version: number
}

/** Sample merge-field values used by the letter template preview. */
export const LETTER_SAMPLE_VALUES: Record<string, string> = {
  candidate_name: 'Kiran Rao',
  employee_name: 'Kiran Rao',
  position: 'Senior Backend Engineer',
  location: 'Bengaluru',
  ctc: '₹24,00,000',
  deadline: '2026-07-16',
  duration: '6',
  joining_date: '2026-07-20',
  effective_date: '2026-07-20',
  company_name: 'Satellite HR',
}

/** Default header/footer applied to seeded letter templates. */
const LETTER_HEADER = '{{company_name}} · Talent Acquisition — [company logo]'
const LETTER_FOOTER =
  'This letter is system generated by {{company_name}} HRMS and is valid without a signature.'

export const seedLetterTemplates: LetterTemplate[] = [
  {
    id: 'tpl-offer-std',
    letterType: 'Offer',
    name: 'Standard Offer Letter',
    description: 'Default offer letter for all employee classes',
    header: LETTER_HEADER,
    footer: LETTER_FOOTER,
    content:
      'Dear {{candidate_name}}, we are pleased to offer you the position of {{position}} at {{location}} with an annual CTC of {{ctc}}. Please respond by {{deadline}}.',
    mergeFields: ['candidate_name', 'position', 'location', 'ctc', 'deadline'],
    active: true,
    version: 3,
  },
  {
    id: 'tpl-offer-intern',
    letterType: 'Offer',
    name: 'Internship Offer Letter',
    description: 'Offer letter for intern employee class',
    header: LETTER_HEADER,
    footer: LETTER_FOOTER,
    content:
      'Dear {{candidate_name}}, we are pleased to offer you an internship as {{position}} for {{duration}} months.',
    mergeFields: ['candidate_name', 'position', 'duration'],
    active: false,
    version: 1,
  },
  {
    id: 'tpl-joining',
    letterType: 'Joining',
    name: 'Joining Letter',
    description: 'Issued after offer acceptance, before start date',
    header: LETTER_HEADER,
    footer: LETTER_FOOTER,
    content:
      'Dear {{candidate_name}}, your joining date is {{joining_date}}. Please report to {{location}} with the listed documents.',
    mergeFields: ['candidate_name', 'joining_date', 'location'],
    active: true,
    version: 2,
  },
  {
    id: 'tpl-appointment',
    letterType: 'Appointment',
    name: 'Appointment Letter',
    description: 'Formal appointment letter issued once status is Joined',
    header: LETTER_HEADER,
    footer: LETTER_FOOTER,
    content:
      'Dear {{employee_name}}, this confirms your appointment as {{position}} effective {{effective_date}}.',
    mergeFields: ['employee_name', 'position', 'effective_date'],
    active: true,
    version: 2,
  },
  {
    id: 'tpl-cancel',
    letterType: 'Cancel Offer',
    name: 'Offer Cancellation Letter',
    description: 'Issued when a released offer is withdrawn by the company',
    header: LETTER_HEADER,
    footer: LETTER_FOOTER,
    content:
      'Dear {{candidate_name}}, we regret to inform you that the offer for {{position}} has been withdrawn.',
    mergeFields: ['candidate_name', 'position'],
    active: true,
    version: 1,
  },
  {
    id: 'tpl-confirmation',
    letterType: 'Confirmation',
    name: 'Confirmation Letter',
    description: 'Confirms employment on successful probation completion',
    header: LETTER_HEADER,
    footer: LETTER_FOOTER,
    content:
      'Dear {{employee_name}}, we are pleased to confirm your employment as {{position}} effective {{effective_date}}.',
    mergeFields: ['employee_name', 'position', 'effective_date'],
    active: true,
    version: 1,
  },
  {
    id: 'tpl-probation-ext',
    letterType: 'Probation Extension',
    name: 'Probation Extension Letter',
    description: 'Extends the probation period with a revised review date',
    header: LETTER_HEADER,
    footer: LETTER_FOOTER,
    content:
      'Dear {{employee_name}}, your probation as {{position}} is extended by {{duration}} months, with a review on {{effective_date}}.',
    mergeFields: ['employee_name', 'position', 'duration', 'effective_date'],
    active: true,
    version: 1,
  },
]

/** Scorecard evaluation criterion (TA-09, TA-16). */
export interface ScorecardCriterion {
  id: string
  name: string
  scaleMax: number
  weight: number
  active: boolean
}

export const seedScorecardCriteria: ScorecardCriterion[] = [
  { id: 'cr-1', name: 'Technical depth', scaleMax: 5, weight: 35, active: true },
  { id: 'cr-2', name: 'Problem solving', scaleMax: 5, weight: 30, active: true },
  { id: 'cr-3', name: 'Communication', scaleMax: 5, weight: 20, active: true },
  { id: 'cr-4', name: 'Culture add', scaleMax: 5, weight: 15, active: true },
]

/** Position titles used by applicability pickers across config screens. */
export const RECRUITMENT_POSITIONS = [
  'Senior Backend Engineer',
  'Sales Development Rep',
  'Customer Support Lead',
  'QA Automation Engineer',
  'DevOps Engineer',
  'Data Engineer',
] as const

/**
 * Interview panel (TA-07) — scoped by the PDF's cascading location →
 * departments → positions applicability.
 */
export interface InterviewPanel {
  id: string
  name: string
  members: string[]
  description?: string
  applicableLocation?: string
  applicableDepartments?: string[]
  applicablePositions?: string[]
}

export const seedPanels: InterviewPanel[] = [
  {
    id: 'pn-1',
    name: 'Backend Panel',
    members: ['Ananya Sharma', 'Dev Patel', 'Ritu Saxena'],
    description: 'Technical screens and system design for backend roles',
    applicableLocation: 'Bengaluru',
    applicableDepartments: ['Engineering'],
    applicablePositions: ['Senior Backend Engineer', 'DevOps Engineer', 'Data Engineer'],
  },
  {
    id: 'pn-2',
    name: 'Design Panel',
    members: ['Divya Menon', 'Tara Bhatt'],
    description: 'Portfolio and craft reviews for design hires',
    applicableLocation: 'All',
    applicableDepartments: ['Product'],
    applicablePositions: [],
  },
  {
    id: 'pn-3',
    name: 'Sales Panel',
    members: ['Karthik Rao', 'Nilesh Shah'],
    description: 'Role plays and pitch evaluation for sales hiring',
    applicableLocation: 'Mumbai',
    applicableDepartments: ['Sales', 'Customer Support'],
    applicablePositions: ['Sales Development Rep', 'Customer Support Lead'],
  },
  {
    id: 'pn-4',
    name: 'Leadership Panel',
    members: ['Sunita Patil', 'Ananya Sharma'],
    description: 'Values and leadership rounds across all departments',
    applicableLocation: 'All',
    applicableDepartments: [],
    applicablePositions: [],
  },
]

/** Sequential interview rounds mapped to panels (TA-41). */
export interface RoundsConfig {
  id: string
  name: string
  employeeClass: string
  location: string
  department: string
  position: string
  rounds: Array<{
    round: number
    name: string
    panelId: string
    /** Mandatory rounds cannot be skipped when scheduling. */
    mandatory?: boolean
  }>
}

export const seedRoundsConfigs: RoundsConfig[] = [
  {
    id: 'rc-1',
    name: 'Engineering Hiring Loop',
    employeeClass: 'Full-time',
    location: 'All',
    department: 'Engineering',
    position: 'All',
    rounds: [
      { round: 1, name: 'Technical Screen', panelId: 'pn-1', mandatory: true },
      { round: 2, name: 'System Design', panelId: 'pn-1', mandatory: true },
      { round: 3, name: 'Leadership & Values', panelId: 'pn-4', mandatory: false },
    ],
  },
  {
    id: 'rc-2',
    name: 'Sales Hiring Loop',
    employeeClass: 'All',
    location: 'All',
    department: 'Sales',
    position: 'All',
    rounds: [
      { round: 1, name: 'Role Play', panelId: 'pn-3', mandatory: true },
      { round: 2, name: 'Manager Round', panelId: 'pn-4', mandatory: false },
    ],
  },
]

/** Weighted pre-interview questionnaire item (TA-43). */
export interface PreInterviewQuestion {
  id: string
  category: string
  question: string
  questionType: 'Objective' | 'Subjective'
  fieldType: 'Text' | 'Number' | 'Yes/No' | 'Choice'
  positionLevel: string
  employeeClass: string
  value: number
  score: number
  mandatory: boolean
  weightage: number
}

export const seedPreInterviewQuestions: PreInterviewQuestion[] = [
  {
    id: 'pq-1',
    category: 'Experience',
    question: 'Years of relevant experience',
    questionType: 'Objective',
    fieldType: 'Number',
    positionLevel: 'Senior',
    employeeClass: 'Full-time',
    value: 6,
    score: 10,
    mandatory: true,
    weightage: 40,
  },
  {
    id: 'pq-2',
    category: 'Availability',
    question: 'Notice period (days)',
    questionType: 'Objective',
    fieldType: 'Number',
    positionLevel: 'All',
    employeeClass: 'All',
    value: 30,
    score: 5,
    mandatory: true,
    weightage: 25,
  },
  {
    id: 'pq-3',
    category: 'Compensation',
    question: 'Expected CTC within band?',
    questionType: 'Objective',
    fieldType: 'Yes/No',
    positionLevel: 'All',
    employeeClass: 'All',
    value: 1,
    score: 5,
    mandatory: false,
    weightage: 35,
  },
]

export const PUBLISH_MODES = ['Real Time', 'Manual'] as const
export type PublishMode = (typeof PUBLISH_MODES)[number]

/** Default post template used when a channel has none configured. */
export const DEFAULT_POST_TEMPLATE =
  'We are hiring! {{position}} — {{department}} at {{location}}. Apply now: {{apply_link}}'

/** Posting channel master (TA-37). */
export interface PostingChannel {
  id: string
  name: string
  channel: string
  type: 'Job Board' | 'Social' | 'Internal' | 'Agency'
  postingMode: 'Internal' | 'External' | 'Both'
  applicability: string
  active: boolean
  /** App key/secret per the PDF's Facebook-style integration (Social / Job Board only). */
  credentials?: { appKey: string; appSecret: string }
  /** Real Time posts go live on approval; Manual requires an explicit publish. */
  publishMode?: PublishMode
  applicableLocations?: string[]
  applicableDepartments?: string[]
  applicablePositions?: string[]
  /** Merge-field post body used when publishing a vacancy to this channel. */
  postTemplate?: string
}

export const seedPostingChannels: PostingChannel[] = [
  {
    id: 'ch-01',
    name: 'LinkedIn Jobs',
    channel: 'linkedin.com',
    type: 'Social',
    postingMode: 'External',
    applicability: 'All departments',
    active: true,
    credentials: { appKey: 'li-app-8842', appSecret: '••••••••' },
    publishMode: 'Real Time',
    applicableLocations: ['All'],
    applicableDepartments: ['All'],
    applicablePositions: ['All'],
    postTemplate: DEFAULT_POST_TEMPLATE,
  },
  {
    id: 'ch-02',
    name: 'Naukri',
    channel: 'naukri.com',
    type: 'Job Board',
    postingMode: 'External',
    applicability: 'All departments',
    active: true,
    credentials: { appKey: 'nk-app-3319', appSecret: '••••••••' },
    publishMode: 'Manual',
    applicableLocations: ['All'],
    applicableDepartments: ['All'],
    applicablePositions: ['All'],
    postTemplate: DEFAULT_POST_TEMPLATE,
  },
  {
    id: 'ch-03',
    name: 'Company Careers Site',
    channel: 'careers.satellitehr.in',
    type: 'Internal',
    postingMode: 'Both',
    applicability: 'All departments',
    active: true,
    publishMode: 'Real Time',
    applicableLocations: ['All'],
    applicableDepartments: ['All'],
    applicablePositions: ['All'],
    postTemplate: DEFAULT_POST_TEMPLATE,
  },
  {
    id: 'ch-04',
    name: 'TalentEdge Agency',
    channel: 'agency',
    type: 'Agency',
    postingMode: 'External',
    applicability: 'Leadership roles',
    active: false,
    publishMode: 'Manual',
    applicableLocations: ['Bengaluru', 'Mumbai'],
    applicableDepartments: ['Engineering', 'Sales'],
    applicablePositions: ['All'],
    postTemplate: DEFAULT_POST_TEMPLATE,
  },
]

/** Posting-source approver rule (TA-38). */
export interface PostingApproverRule {
  id: string
  postingMode: 'Internal' | 'External' | 'Both'
  employeeClass: string
  location: string
  approvers: string[]
}

export const seedPostingApproverRules: PostingApproverRule[] = [
  { id: 'pa-1', postingMode: 'External', employeeClass: 'All', location: 'All', approvers: ['Sunita Patil'] },
  { id: 'pa-2', postingMode: 'Internal', employeeClass: 'All', location: 'All', approvers: ['Divya Menon'] },
]

export const ASSIGNMENT_METHODS = ['manual', 'round-robin', 'workload'] as const
export type AssignmentMethod = (typeof ASSIGNMENT_METHODS)[number]

/** Location-based offer approver rule + out-of-band approver (TA-46). */
export interface OfferApproverRule {
  id: string
  locations: string[]
  employeeClass: string
  approvers: string[]
  /** Levels up the hiring manager's hierarchy to include; null = none. */
  hiringManagerHierarchyLevels?: number | null
  /** Named approvers appended after the hierarchy chain. */
  additionalApprovers?: string[]
}

export const seedOfferApproverRules: OfferApproverRule[] = [
  { id: 'oa-1', locations: ['Bengaluru'], employeeClass: 'All', approvers: ['Sunita Patil'], hiringManagerHierarchyLevels: 2, additionalApprovers: ['Priya Deshmukh'] },
  { id: 'oa-2', locations: ['Pune', 'Mumbai'], employeeClass: 'All', approvers: ['Divya Menon', 'Farhan Ali'], hiringManagerHierarchyLevels: 1, additionalApprovers: [] },
  { id: 'oa-3', locations: ['Hyderabad', 'Remote — India'], employeeClass: 'All', approvers: ['Karthik Rao'], hiringManagerHierarchyLevels: null, additionalApprovers: [] },
]

/** Resource-requisition approver rule (TA-52). */
export interface RequisitionApproverRule {
  id: string
  template: string
  employeeClass: string
  location: string
  department: string
  position: string
  approvers: string[]
  /** Levels up the requester's reporting line to include; null = none. */
  reportingManagerHierarchyLevels?: number | null
}

export const seedRequisitionApproverRules: RequisitionApproverRule[] = [
  {
    id: 'ra-1',
    template: 'Standard 2-level',
    employeeClass: 'All',
    location: 'All',
    department: 'All',
    position: 'All',
    approvers: ['Sunita Patil', 'Rohit Bansal'],
    reportingManagerHierarchyLevels: 2,
  },
  {
    id: 'ra-2',
    template: 'Engineering fast-track',
    employeeClass: 'Full-time',
    location: 'Bengaluru',
    department: 'Engineering',
    position: 'All',
    approvers: ['Ananya Sharma', 'Rohit Bansal'],
    reportingManagerHierarchyLevels: null,
  },
]

/** Recruiter / HR role assignment (Kensium: Recruiter Role & HR Role). */
export interface RecruitmentRoleAssignment {
  id: string
  roleName: string
  roleType: 'Recruiter' | 'HR'
  description: string
  applicableLocations: string[]
  applicableDepartments: string[]
  applicablePositions: string[]
  assignedEmployee: string
}

export const seedRoleAssignments: RecruitmentRoleAssignment[] = [
  {
    id: 'role-1',
    roleName: 'Engineering Recruiter',
    roleType: 'Recruiter',
    description: 'Owns sourcing and pipeline for engineering hiring',
    applicableLocations: ['Bengaluru', 'Remote — India'],
    applicableDepartments: ['Engineering'],
    applicablePositions: ['Senior Backend Engineer', 'DevOps Engineer', 'Data Engineer'],
    assignedEmployee: 'Meera Iyer',
  },
  {
    id: 'role-2',
    roleName: 'HR Partner — Sales & Support',
    roleType: 'HR',
    description: 'HR sign-offs and joining formalities for sales and support hiring',
    applicableLocations: ['Mumbai', 'Pune'],
    applicableDepartments: ['Sales', 'Customer Support'],
    applicablePositions: ['Sales Development Rep', 'Customer Support Lead'],
    assignedEmployee: 'Sunita Patil',
  },
]

/** Locations a required document rule can be scoped to (TA-54). */
export const REQUIRED_DOC_LOCATIONS = [
  'All',
  'Bengaluru',
  'Pune',
  'Mumbai',
  'Hyderabad',
  'Remote — India',
] as const

/** Stage-based required candidate document (TA-54). */
export interface RequiredDocument {
  id: string
  name: string
  docType: 'Identity' | 'Education' | 'Employment' | 'Compensation'
  employeeClass: string
  requiredAtStage: string
  applicableLocations: string[]
}

export const seedRequiredDocuments: RequiredDocument[] = [
  { id: 'doc-1', name: 'PAN Card', docType: 'Identity', employeeClass: 'All', requiredAtStage: 'offer', applicableLocations: ['All'] },
  { id: 'doc-2', name: 'Degree Certificate', docType: 'Education', employeeClass: 'Full-time', requiredAtStage: 'reference-check', applicableLocations: ['All'] },
  { id: 'doc-3', name: 'Last 3 Payslips', docType: 'Compensation', employeeClass: 'Full-time', requiredAtStage: 'offer', applicableLocations: ['Bengaluru', 'Pune', 'Mumbai'] },
  { id: 'doc-4', name: 'Relieving Letter', docType: 'Employment', employeeClass: 'All', requiredAtStage: 'hired', applicableLocations: ['Hyderabad', 'Remote — India'] },
]

/** Rehire carry-over configuration tabs (TA-55). */
export const REHIRE_TABS = [
  { tab: 'Personal Details', fields: ['Name & DOB', 'Marital status', 'Nationality', 'Photo'] },
  { tab: 'Contact Details', fields: ['Permanent address', 'Emergency contacts', 'Personal email'] },
  { tab: 'Academic Details', fields: ['Degrees', 'Certifications'] },
  { tab: 'Work Experience', fields: ['Prior employers', 'Internal tenure history'] },
  { tab: 'Skills', fields: ['Skill matrix', 'Languages'] },
  { tab: 'Employee Verification', fields: ['Background check result', 'Reference outcomes'] },
  { tab: 'Orientation', fields: ['Policy acknowledgements', 'Compliance trainings'] },
] as const

export const defaultRehireSelections: Record<string, string[]> = {
  'Personal Details': ['Name & DOB', 'Nationality'],
  'Contact Details': ['Permanent address'],
  'Academic Details': ['Degrees', 'Certifications'],
  'Work Experience': ['Prior employers', 'Internal tenure history'],
  Skills: ['Skill matrix'],
  'Employee Verification': [],
  Orientation: [],
}

/** Recruiter strengths profile (TA-56). */
export interface RecruiterStrength {
  id: string
  recruiter: string
  strengths: string
  applicability: string
}

export const seedRecruiterStrengths: RecruiterStrength[] = [
  { id: 'rs-1', recruiter: 'Meera Iyer', strengths: 'Backend & platform engineering', applicability: 'Engineering' },
  { id: 'rs-2', recruiter: 'Sana Qureshi', strengths: 'High-volume sales hiring', applicability: 'Sales, Customer Support' },
  { id: 'rs-3', recruiter: 'Vikram Joshi', strengths: 'Data & analytics roles', applicability: 'Engineering, Product' },
]

/** Talent-pool mailbox import settings (TA-40). */
export interface MailboxSettings {
  enabled: boolean
  server: string
  username: string
  port: number
  encryption: 'SSL' | 'TLS' | 'None'
  checkingIntervalMins: number
  timeoutSecs: number
  deleteAfterImport: boolean
  notifyNonShortlisted: boolean
  /** Use the email address itself as the login username. */
  emailAsUsername: boolean
  /** Skip a poll if the previous import run is still in progress. */
  noNewInstanceWhileRunning: boolean
  /** Comma-separated subject words that exclude a mail from import. */
  ignoreSubjectWords: string
  /** Comma-separated sender ids that exclude a mail from import. */
  ignoreSenderIds: string
}

export const defaultMailboxSettings: MailboxSettings = {
  enabled: true,
  server: 'imap.satellitehr.in',
  username: 'applications@satellitehr.in',
  port: 993,
  encryption: 'SSL',
  checkingIntervalMins: 15,
  timeoutSecs: 60,
  deleteAfterImport: true,
  notifyNonShortlisted: false,
  emailAsUsername: true,
  noNewInstanceWhileRunning: true,
  ignoreSubjectWords: 'Out of office, Auto-reply, Undeliverable',
  ignoreSenderIds: 'no-reply@, mailer-daemon@',
}

/** Pre-onboarding checklist question (TA-51). */
export interface ChecklistQuestion {
  id: string
  responseFrom: 'Candidate' | 'HR' | 'IT'
  question: string
  questionType: 'Objective' | 'Subjective'
  fieldType: 'Text' | 'Yes/No' | 'Date'
  displayType: 'Input' | 'Dropdown' | 'Checkbox'
  value: string
  mandatory: boolean
}

export const seedChecklistQuestions: ChecklistQuestion[] = [
  {
    id: 'cq-1',
    responseFrom: 'Candidate',
    question: 'Background verification consent received?',
    questionType: 'Objective',
    fieldType: 'Yes/No',
    displayType: 'Checkbox',
    value: 'Yes',
    mandatory: true,
  },
  {
    id: 'cq-2',
    responseFrom: 'HR',
    question: 'Identity documents collected',
    questionType: 'Subjective',
    fieldType: 'Text',
    displayType: 'Input',
    value: '',
    mandatory: true,
  },
  {
    id: 'cq-3',
    responseFrom: 'IT',
    question: 'Laptop & network access requested',
    questionType: 'Objective',
    fieldType: 'Yes/No',
    displayType: 'Checkbox',
    value: '',
    mandatory: false,
  },
  {
    id: 'cq-4',
    responseFrom: 'IT',
    question: 'Employee ID creation requested?',
    questionType: 'Objective',
    fieldType: 'Yes/No',
    displayType: 'Checkbox',
    value: '',
    mandatory: false,
  },
  {
    id: 'cq-5',
    responseFrom: 'HR',
    question: 'Welcome kit prepared?',
    questionType: 'Objective',
    fieldType: 'Yes/No',
    displayType: 'Checkbox',
    value: '',
    mandatory: false,
  },
  {
    id: 'cq-6',
    responseFrom: 'HR',
    question: 'Joining date confirmed with candidate?',
    questionType: 'Objective',
    fieldType: 'Date',
    displayType: 'Input',
    value: '',
    mandatory: true,
  },
]

/** Departments that can own a joining formality (notified when it is due). */
export const FORMALITY_DEPARTMENTS = [
  'Human Resources',
  'IT & Systems',
  'Administration',
  'Finance',
] as const

/** Joining formalities checklist item (Kensium PDF — Joining Formalities). */
export interface JoiningFormality {
  id: string
  item: string
  description: string
  responsibleDepartment: string
  timing: 'before-joining' | 'after-joining'
  /** Days before/after the joining date by which the item must complete. */
  toBeCompletedByDays: number
  displayOrder: number
}

export const seedJoiningFormalities: JoiningFormality[] = [
  {
    id: 'jf-1',
    item: 'BGV initiation',
    description: 'Trigger background verification with the empanelled vendor',
    responsibleDepartment: 'Human Resources',
    timing: 'before-joining',
    toBeCompletedByDays: 7,
    displayOrder: 1,
  },
  {
    id: 'jf-2',
    item: 'Workstation allocation',
    description: 'Laptop, network access and software licences provisioned',
    responsibleDepartment: 'IT & Systems',
    timing: 'before-joining',
    toBeCompletedByDays: 2,
    displayOrder: 2,
  },
  {
    id: 'jf-3',
    item: 'ID card issuance',
    description: 'Photo capture and access-card printing on the first day',
    responsibleDepartment: 'Administration',
    timing: 'after-joining',
    toBeCompletedByDays: 1,
    displayOrder: 3,
  },
  {
    id: 'jf-4',
    item: 'Welcome kit handover',
    description: 'Company handbook, merchandise and buddy introduction',
    responsibleDepartment: 'Human Resources',
    timing: 'after-joining',
    toBeCompletedByDays: 3,
    displayOrder: 4,
  },
]

/** Tenant-defined custom field (TA-26, TA-30). */
export interface CustomFieldDef {
  id: string
  entity: 'requisition' | 'candidate' | 'application'
  label: string
  fieldType: 'text' | 'number' | 'select'
  options?: string[]
  mandatory: boolean
  active: boolean
  version: number
  effectiveFrom: string
}

export const seedCustomFields: CustomFieldDef[] = [
  {
    id: 'cf-band',
    entity: 'requisition',
    label: 'Compensation band',
    fieldType: 'select',
    options: ['B1', 'B2', 'B3', 'B4'],
    mandatory: false,
    active: true,
    version: 2,
    effectiveFrom: '2026-04-01',
  },
  {
    id: 'cf-visa',
    entity: 'candidate',
    label: 'Work authorization',
    fieldType: 'text',
    mandatory: false,
    active: true,
    version: 1,
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'cf-notice',
    entity: 'application',
    label: 'Notice period (days)',
    fieldType: 'number',
    mandatory: true,
    active: true,
    version: 1,
    effectiveFrom: '2026-01-01',
  },
]

/** Versioned approver-graph publications (TA-25). */
export interface ApproverGraphVersion {
  version: number
  author: string
  effectiveFrom: string
  summary: string
  status: 'active' | 'superseded' | 'draft'
}

export const seedApproverGraphVersions: ApproverGraphVersion[] = [
  {
    version: 1,
    author: 'Sunita Patil',
    effectiveFrom: '2026-01-01',
    summary: 'Single-level HR approval for all requisitions',
    status: 'superseded',
  },
  {
    version: 2,
    author: 'Sunita Patil',
    effectiveFrom: '2026-04-01',
    summary: 'Added Finance level; non-budgeted positions route to Priya Deshmukh',
    status: 'active',
  },
]

/** Platform-admin tenant provisioning (TA-21, TA-23). */
export interface Tenant {
  id: string
  name: string
  moduleEnabled: boolean
  calendarIntegration: boolean
  onboardingIntegration: boolean
  rlsActive: boolean
}

export const seedTenants: Tenant[] = [
  { id: 't-1', name: 'Aurora Retail Pvt Ltd', moduleEnabled: true, calendarIntegration: true, onboardingIntegration: true, rlsActive: true },
  { id: 't-2', name: 'Bluegrid Logistics', moduleEnabled: true, calendarIntegration: false, onboardingIntegration: true, rlsActive: true },
  { id: 't-3', name: 'Crestline Finserv', moduleEnabled: false, calendarIntegration: false, onboardingIntegration: false, rlsActive: true },
]

/** Shared-engine log entry (TA-27, TA-28, TA-29, TA-30). */
export interface EngineLogEntry {
  id: string
  at: string
  engine: 'workflow' | 'rules' | 'notification' | 'forms'
  event: string
  detail: string
  actor: string
}

export const seedEngineLog: EngineLogEntry[] = [
  {
    id: 'el-1',
    at: '2026-06-24T10:02:00Z',
    engine: 'workflow',
    event: 'Offer OFR-503 routed',
    detail: 'Out-of-band CTC matched rule oa-3 + out-of-band approver — routed to Rohit Bansal (L2)',
    actor: 'Workflow Engine',
  },
  {
    id: 'el-2',
    at: '2026-06-20T09:31:00Z',
    engine: 'notification',
    event: 'Offer released',
    detail: 'Template "Offer Released" v3 rendered and dispatched to kiran.rao@gmail.com (Email)',
    actor: 'Notification Engine',
  },
  {
    id: 'el-3',
    at: '2026-06-18T14:12:00Z',
    engine: 'rules',
    event: 'Stage gate evaluated',
    detail: 'app-01 → offer: 2/2 scorecards complete, 2/2 references complete — ALLOW',
    actor: 'Rules Engine',
  },
  {
    id: 'el-4',
    at: '2026-06-10T08:00:00Z',
    engine: 'forms',
    event: 'Requisition form rendered',
    detail: 'Rendered v2 field metadata (custom field "Compensation band" included)',
    actor: 'Forms Engine',
  },
]

/** Group-company governance standards (TA-19). */
export interface GroupStandard {
  id: string
  area: string
  standard: string
  override: 'not-allowed' | 'within-limits' | 'free'
}

export const seedGroupStandards: GroupStandard[] = [
  {
    id: 'gs-1',
    area: 'Requisition approvals',
    standard: 'Minimum 2 approval levels; Finance sign-off mandatory',
    override: 'not-allowed',
  },
  {
    id: 'gs-2',
    area: 'Offer templates',
    standard: 'Group master offer template v3 with statutory clauses',
    override: 'within-limits',
  },
  {
    id: 'gs-3',
    area: 'Scorecard criteria',
    standard: '4 core criteria with fixed weightings',
    override: 'within-limits',
  },
]

/** Portfolio-level company metrics (TA-20). */
export interface CompanyMetrics {
  company: string
  openRequisitions: number
  activeCandidates: number
  offersExtended: number
  offerAcceptanceRate: number
  avgTimeToHireDays: number
}

export const seedPortfolioMetrics: CompanyMetrics[] = [
  { company: 'Aurora Retail Pvt Ltd', openRequisitions: 14, activeCandidates: 86, offersExtended: 9, offerAcceptanceRate: 78, avgTimeToHireDays: 34 },
  { company: 'Bluegrid Logistics', openRequisitions: 6, activeCandidates: 31, offersExtended: 4, offerAcceptanceRate: 50, avgTimeToHireDays: 41 },
  { company: 'Crestline Finserv', openRequisitions: 9, activeCandidates: 44, offersExtended: 6, offerAcceptanceRate: 83, avgTimeToHireDays: 28 },
]

export const APPROVER_DIRECTORY = [
  'Sunita Patil',
  'Rohit Bansal',
  'Priya Deshmukh',
  'Divya Menon',
  'Karthik Rao',
  'Farhan Ali',
  'Ananya Sharma',
] as const

/** Recruitment email template (Kensium: Email Templates, EMT-01…EMT-03). */
export interface RecruitmentEmailTemplate {
  id: string
  name: string
  emailType: string
  description: string
  subject: string
  body: string
  active: boolean
}

const EMAIL_TEMPLATE_SOURCE: Array<[name: string, emailType: string, description: string]> = [
  ['Requisition Submitted', 'Requisition', 'Sent to approvers when a resource requisition is submitted'],
  ['Requisition Approved', 'Requisition', 'Notifies the requester that the requisition is approved'],
  ['Requisition Rejected', 'Requisition', 'Notifies the requester that the requisition was rejected'],
  ['Requisition Cancelled', 'Requisition', 'Confirms cancellation of an open requisition'],
  ['Posting Approval Request', 'Posting', 'Requests approval before an external posting goes live'],
  ['Posting Published', 'Posting', 'Confirms a vacancy has been published to a channel'],
  ['Posting Expired', 'Posting', 'Alerts the recruiter that a posting has lapsed'],
  ['Application Received', 'Application', 'Acknowledges a new application to the candidate'],
  ['Application Shortlisted', 'Application', 'Tells the candidate they have been shortlisted'],
  ['Application On Hold', 'Application', 'Tells the candidate their application is on hold'],
  ['Application Rejected', 'Application', 'Regret email for non-shortlisted candidates'],
  ['Pre-Interview Questionnaire', 'Application', 'Sends the weighted pre-interview questionnaire link'],
  ['Interview Scheduled', 'Interview', 'Invitation with date, time and panel for a round'],
  ['Interview Rescheduled', 'Interview', 'Updated invitation after a slot change'],
  ['Interview Cancelled', 'Interview', 'Cancels a scheduled interview round'],
  ['Interview Reminder — Candidate', 'Interview', 'Reminds the candidate 24 hours before the round'],
  ['Interview Reminder — Panel', 'Interview', 'Reminds panel members of upcoming interviews'],
  ['Scorecard Pending Reminder', 'Interview', 'Nudges interviewers with unsubmitted scorecards'],
  ['Reference Check Request', 'Reference', 'Emails the referee the reference questionnaire'],
  ['Reference Check Reminder', 'Reference', 'Reminds a referee about a pending reference'],
  ['Reference Check Completed', 'Reference', 'Confirms all references are complete for a candidate'],
  ['Offer Approval Request', 'Offer', 'Routes a drafted offer to the mapped approvers'],
  ['Offer Approved', 'Offer', 'Tells the recruiter the offer cleared approvals'],
  ['Offer Released', 'Offer', 'Delivers the offer letter to the candidate'],
  ['Offer Accepted', 'Offer', 'Confirms candidate acceptance to the hiring team'],
  ['Offer Declined', 'Offer', 'Notifies the hiring team of a declined offer'],
  ['Offer Withdrawn', 'Offer', 'Informs the candidate the offer was withdrawn'],
  ['Offer Expiry Reminder', 'Offer', 'Reminds the candidate before the offer deadline'],
  ['Joining Letter', 'Onboarding', 'Sends the joining letter after acceptance'],
  ['Appointment Letter', 'Onboarding', 'Sends the appointment letter once status is Joined'],
  ['Pre-Onboarding Checklist', 'Onboarding', 'Shares the pre-onboarding checklist with the candidate'],
  ['Document Upload Request', 'Onboarding', 'Requests stage-based required documents'],
  ['Background Verification Initiated', 'Onboarding', 'Tells the candidate BGV has started'],
  ['Candidate Portal Invitation', 'Portal', 'Invites the candidate to the self-service portal'],
]

export const seedEmailTemplates: RecruitmentEmailTemplate[] =
  EMAIL_TEMPLATE_SOURCE.map(([name, emailType, description], i) => ({
    id: `emt-${String(i + 1).padStart(2, '0')}`,
    name,
    emailType,
    description,
    subject: `${name} — {{candidate_name}}`,
    body: `Dear {{recipient_name}},\n\n${description}. This message was generated from the "${name}" recruitment template.\n\nRegards,\n{{company_name}} Talent Acquisition`,
    active: i !== 6 && i !== 9,
  }))

/** Recruitment expense head (Kensium: Expense Head, EXH-01…EXH-03). */
export interface ExpenseHead {
  id: string
  name: string
  description: string
}

export const seedExpenseHeads: ExpenseHead[] = [
  { id: 'exh-1', name: 'Job Board Fees', description: 'Paid listings on external job boards (Naukri, LinkedIn)' },
  { id: 'exh-2', name: 'Agency Commission', description: 'Placement fees payable to recruitment agencies' },
  { id: 'exh-3', name: 'Candidate Travel', description: 'Reimbursed travel for onsite interview rounds' },
  { id: 'exh-4', name: 'Assessment Tools', description: 'Licences for coding tests and psychometric assessments' },
  { id: 'exh-5', name: 'Referral Bonus', description: 'Employee referral payouts on successful joins' },
]

/** Position-level pay grades (Kensium: Position Level PayGrade, PLP-01/02). */
export const PAY_GRADES = ['PG-1', 'PG-2', 'PG-3', 'PG-4', 'PG-5'] as const

export interface PositionLevelPaygrade {
  id: string
  positionLevel: string
  payGrade: string
  minCtcLpa: number
  maxCtcLpa: number
}

export const seedPaygradeMappings: PositionLevelPaygrade[] = [
  { id: 'plp-1', positionLevel: 'Junior', payGrade: 'PG-1', minCtcLpa: 4, maxCtcLpa: 8 },
  { id: 'plp-2', positionLevel: 'Mid', payGrade: 'PG-2', minCtcLpa: 8, maxCtcLpa: 16 },
  { id: 'plp-3', positionLevel: 'Senior', payGrade: 'PG-3', minCtcLpa: 16, maxCtcLpa: 28 },
  { id: 'plp-4', positionLevel: 'Lead', payGrade: 'PG-4', minCtcLpa: 24, maxCtcLpa: 40 },
]

/** Reference-check policy (Kensium: Reference Check, RFC-01…RFC-03). */
export interface ReferenceCheckSettings {
  inHouse: boolean
  viaEmail: boolean
  minReferences: number
}

export const defaultReferenceCheckSettings: ReferenceCheckSettings = {
  inHouse: true,
  viaEmail: true,
  minReferences: 2,
}
